FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o mockserver ./internal/mockserver

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/mockserver .
EXPOSE 3001
CMD ["./mockserver"]
